# @package _group_
name: human_action
frames_shift: 1 # of frames to shift
num_frames: 20
img_width: 128
grey_scale: True # if true save grey scale gif 
actions: # action to use (walking, jogging, running, boxing, handwaving and handclapping)
  - walking