# @package _group_
name: human_action
num_frames: 10
img_width: 128
grey_scale: True # if true save grey scale gif 
actions: # action to use (walking, jogging, running, boxing, handwaving and handclapping)
  - walking