# @package _group_

num_data: 5000
len_seq: 10
img_width: 128
img_channel: 1
max_intensity: 1
motions: # motion to use (walking, jogging, running, boxing, handwaving and handclapping)
  - walking
  - jogging
  - running
  - handwaving
  - handclapping