# @package _group_
name: human_action
frames_shift: 10 # of frames to shift
num_frames: 10
img_width: 128
img_channel: 1
grey_scale: True # if true save grey scale gif 
actions: # action to use (walking, jogging, running, boxing, handwaving and handclapping)
  - walking