# @package _group_

num_frames: 10
img_width: 128
actions: # action to use (walking, jogging, running, boxing, handwaving and handclapping)
  - walking
  - jogging
  - running
  - handwaving
  - handclapping