# @package _group_

reverse_scheduled_sampling: 0
r_sampling_step_1: 25000
r_sampling_step_2: 50000
r_exp_alpha: 5000
scheduled_sampling: 1
sampling_stop_iter: 50000
sampling_start_value: 1.0
sampling_changing_rate: 0.00002
