defaults:
 - dataset: moving_mnist
mlrun_path: /home/data/ryoto/PredRNN/mlruns/
experiment:
  name: Default

# Training configs
train:
  epochs: 5
  batch_size: 2
  device: cuda:1
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: best_ckpt.pth
  lr: 0.0001
  val_percent: 0.1 # Percent of the data that is used as validation (0-1)

# Model configs
model:
  name: predrnn
  load: False
  input_num: 4
  num_hidden: [64,64,64,64]
  filter_size: 5
  stride: 1
  patch_size: 4
  layer_norm: 1

sampling:
  reverse_scheduled_sampling: 0
  r_sampling_step_1: 25000
  r_sampling_step_2: 50000
  r_exp_alpha: 5000
  scheduled_sampling: 1
  sampling_stop_iter: 50000
  sampling_start_value: 1.0
  sampling_changing_rate: 0.00002
  


test:
  load_model: "/home/data/ryoto/Unet/mlruns/2/e8ab44a681604eb9aaac31c6a4b26bfd/artifacts/best_ckpt.pth" # Load model from a .pth file
  batch_size: 8
  device: cuda:1
  num_workers: 2
  decouple_beta: 0.1
